os: linux
dist: bionic

services: docker

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache

jobs:
  include:
    - php: 7.4
      env: WP_VERSION=5.5
    - php: 7.3
      env: WP_VERSION=5.5
    - php: 7.3
      env: WP_VERSION=5.4
    - php: 7.3
      env: WP_VERSION=5.3
    - php: 7.2
      env: WP_VERSION=5.5
    - php: 7.2
      env: WP_VERSION=5.4
    - php: 7.2
      env: WP_VERSION=5.3

before_script:
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - |
    if [[ ! -z "$DOCKER_TESTS" ]] ; then
      docker-compose up -d
    fi
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      composer install
      bash bin/install-wp-tests.sh wordpress_test root '' localhost "$WP_VERSION"
      composer global require "phpunit/phpunit=7.*"
      ./vendor/bin/phpunit --version
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      composer global require wp-coding-standards/wpcs
      ./vendor/bin/phpcs --config-set installed_paths ./vendor/wp-coding-standards/wpcs
    fi

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      ./vendor/bin/phpunit --version
      ./vendor/bin/phpunit
      WP_MULTISITE=1 ./vendor/bin/phpunit
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      ./vendor/bin/phpcs
    fi

env: # Environments
  - TMPDIR=/tmp WP_TESTS_DIR=/tmp/wordpress-tests-lib WP_CORE_DIR=/srv/wordpress/html DOCKER_TESTS=false
